### PR TITLE
Merge React 0.14 changes from other forks

### PR DESCRIPTION
**Pull request by lolJS**

### CODE REVIEW

**Comment by freiksenet** [comment]
Thanks! Are you willing to maintain this project? I don't have time to do it currently and I don't use it anywhere in production.

**Comment by freiksenet** [comment]
I generally consider it a failed experiment, modifying and cloning children is expensive and not very handy as an API, but I don't mind keeping it if people are interested.

**Comment by lolJS** [comment]
Hey, I liked the modularity of the project and it provided a lot more flexibility than other components...That being said I'm willing to maintain and improve it :+1:!

**Comment by freiksenet** [comment]
I agree that my premise was good :D I'd change the way I modularized, instead of passing children, I'd pass functions that return components and this way customize the rendering.

**Comment by freiksenet** [comment]
I'll add you to collaborators.

**Pull request merged**
